### ISSUE TITLE
useScrollbar's scrollTo always throws errores/doesn't work

### ISSUE THREAD

**Issue by Anemolo** [14islands/r3f-scroll-rig#19]
Hello,

Tried to animate the scroll to top of page (to then trigger a transition animation) with useScrollbar scrollTo, however seems to be not working correctly. Always throws errors:

Codesandbox: https://codesandbox.io/s/hello-scrollscene-forked-wo9fdr?file=/src/App.jsx

```
Uncaught TypeError: Cannot read properties of undefined (reading 'stop')
    at Object.scrollTo (lenis.modern.mjs:167:127)
    at eval (App.jsx:53:15)
```

Doesn't seem to be an issue on Lenis latest issue as showcased in this demo using Latest lenis and using their scrollTo:
Codesandbox: https://codesandbox.io/s/still-forest-jh6rnx

**Comment by sushanyadav** [comment]
any updates on this ? running through the same issue.

**Comment by ayungavis** [comment]
+1 @ffdead

**Comment by ffdead** [comment]
Will take a look today!

**Comment by ffdead** [comment]
Hi guys, please try `v8.11.1`

Since lenis is created as a side effect you need to also call the scrollTo in a useEffect (or from a user interaction):

```jsx
  const scrollbar = useScrollbar();

  useEffect(() => {
    scrollbar.scrollTo(10000, { duration: 5 });
  }, [scrollbar]);
  ```
  Important to add `scrollbar` as a dep to the useEffect since it won't have created lenis on the first render. 
  
 **Option 2**
 You can also grab a ref to the scrollbar:
 
 ```jsx
 const scrollbar = useRef()
 
 return (
     <SmoothScrollbar ref={scrollbar}>
 )
 ```
 
 This ref is allows imperative calls to the following methods: 

<img width="646" alt="Screenshot 2023-05-05 at 10 52 05" src="https://user-images.githubusercontent.com/420472/236415703-530f1d19-3387-47c5-a0c5-02fe5186d142.png">

**Comment by sushanyadav** [comment]
Thank you @ffdead .
works perfectly. in `v8.11.1`
